framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              retry_strategy:
                max_retries: 3
                multiplier: 2

        routing:
            'App\DTO\CalculationData': async
